#!/usr/bin/env bash
#
# Copyright (C) 2022-2026 James Cherti
# URL: https://github.com/jamescherti/jc-gentoo-portage
#
# Distributed under terms of the MIT license.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Error: This script must be run as root." >&2
  exit 1
fi

if ! type -P cpuid2cpuflags &>/dev/null; then
  echo "Error: You need to install: app-portage/cpuid2cpuflags" >&2
  exit 1
fi

if [[ ! -d /var/portage-notmpfs ]]; then
  echo "[CREATE DIRECTORY] /var/portage-notmpfs"
  mkdir -p /var/portage-notmpfs
fi

if [[ ! -f /etc/portage/make-local.conf ]]; then
  echo "[CREATE FILE] /etc/portage/make-local.conf"
  touch /etc/portage/make-local.conf
fi

if [[ ! -f /etc/portage/package.use/00cpu-flags ]]; then
  echo "*/* $(cpuid2cpuflags)" >"/etc/portage/package.use/00cpu-flags"
  echo "[CREATE FILE] /etc/portage/package.use/00cpu-flags"
fi
