#!/usr/bin/env bash
#
# Copyright (C) 2022-2026 James Cherti
# URL: https://github.com/jamescherti/jc-gentoo-portage
#
# Distributed under terms of the MIT license.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -euo pipefail
umask 022

# Global variables for paths
readonly PORTAGE_NOTMPFS_DIR="/var/portage-notmpfs"
readonly MAKE_LOCAL_CONF="/etc/portage/make-local.conf"
readonly CPU_FLAGS_FILE="/etc/portage/package.use/00my-cpu-flags"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Error: This script must be run as root." >&2
  exit 1
fi

if ! type -P cpuid2cpuflags &>/dev/null; then
  echo "Error: You need to install: app-portage/cpuid2cpuflags" >&2
  exit 1
fi

# No tmpfs dir
if [[ ! -d "${PORTAGE_NOTMPFS_DIR}" ]]; then
  echo "[CREATE DIRECTORY] ${PORTAGE_NOTMPFS_DIR}"
  mkdir -p "${PORTAGE_NOTMPFS_DIR}"
else
  echo "[IGNORE] ${PORTAGE_NOTMPFS_DIR}"
fi

# CPU flags
if [[ ! -f "${CPU_FLAGS_FILE}" ]]; then
  echo "*/* $(cpuid2cpuflags)" >"${CPU_FLAGS_FILE}"
  echo "[CREATE FILE] ${CPU_FLAGS_FILE}:" "$(cat "${CPU_FLAGS_FILE}")"
else
  echo "[IGNORE] ${CPU_FLAGS_FILE}"
fi

# make-local.conf
if [[ ! -f "${MAKE_LOCAL_CONF}" ]]; then
  echo "[CREATE FILE] ${MAKE_LOCAL_CONF}"
  touch "${MAKE_LOCAL_CONF}"

  if type -P nproc &>/dev/null; then
    NUM_PROCESSORS=$(nproc)
    HALF_PROCESSORS=$((NUM_PROCESSORS / 2))

    if ((HALF_PROCESSORS == 0)); then
      HALF_PROCESSORS=1
    fi

    echo "MAKEOPTS=\"-j${HALF_PROCESSORS} -l${HALF_PROCESSORS}\"" \
      >>"${MAKE_LOCAL_CONF}"
    echo "[ADD] ${MAKE_LOCAL_CONF}:" \
      "MAKEOPTS=\"-j${HALF_PROCESSORS} -l${HALF_PROCESSORS}\""

    echo "NINJAFLAGS=\"\$MAKEOPTS\"" \
      >>"${MAKE_LOCAL_CONF}"
    echo "[ADD] ${MAKE_LOCAL_CONF}:" \
      "NINJAFLAGS=\"\$MAKEOPTS\""
  else
    echo "Warning: The 'nproc' command was not found." >&2
  fi
else
  echo "[IGNORE] ${MAKE_LOCAL_CONF}"
fi
